# Use this .yml template to create a CI/build for You_Source ASP.NET Core 3.1 Project
# Each `env-ci.yml` will have different `trigger`
# By default, this `yml` publishes all `Web Apps` (e.g. APIs, Function Apps) in your solution,
# in your CD (release), pick projects to be deployed to intended Azure Resources

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Litchi.Book.Api/Litchi.Book.Api.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
  displayName: 'Publish Book Projects'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Litchi.BookAdmin.Api/Litchi.BookAdmin.Api.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
  displayName: 'Publish Book Admin Projects'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'
